### ISSUE TITLE
android/ios' auto fill in from keyboard only fills up the first field

### ISSUE THREAD

**Issue by youngjun625** [david-legend/otp_textfield#16]

**Comment by david-legend** [comment]
Provide an image

**Comment by deepakrana0011** [comment]
Yes it fill only first character

**Comment by david-legend** [comment]
I will work on this on the weekend

**Comment by emmett-deen** [comment]
Also having this issue

**Comment by phillipshaong** [comment]
I am also having this issue.

**Comment by Tetsukick** [comment]
I'm also having this issue...
is there any solution?

**Comment by Tetsukick** [comment]
@david-legend
I ve created the PR for this issue. please help to review it.
#21

**Comment by ishantgupta777** [comment]
@david-legend  can you please regarding this issue? or guide

**Comment by Tetsukick** [comment]
@ishantgupta777 
temporary, you can handle paste from my repository like bellow in pubspec.yaml

```
  flutter_otp_text_field:
    git:
      url: https://github.com/Tetsukick/otp_textfield
      ref: f9cd6f5fee2cbd6be58d3d989c7646daaa2afdef
```
