### ISSUE TITLE
Unable to add Copy Paste 

### ISSUE THREAD

**Issue by MachhindraNeupane10** [david-legend/otp_textfield#19]

**Comment by Tetsukick** [comment]
I m also thinking about it. is there any update about it?

**Comment by Tetsukick** [comment]
@david-legend 
I ve created the PR for this issue. please help to review it.
#21

**Comment by Tetsukick** [comment]
@MachhindraNeupane10 
temporary, you can handle paste from my repository like bellow in pubspec.yaml

```
  flutter_otp_text_field:
    git:
      url: https://github.com/Tetsukick/otp_textfield
      ref: f9cd6f5fee2cbd6be58d3d989c7646daaa2afdef
```
